include: https://api.choerodon.com.cn/devops/v1/projects/1529/ci_contents/pipelines/d7d83616-8079-440a-8027-082ae64fda4e/content.yaml

#include: https://api.choerodon.com.cn/devops/v1/projects/1529/ci_contents/pipelines/5dd482ce-f56c-497e-a7bf-6a13747fb039/content.yaml
#
##image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.9.1
##
##stages:
##  - build
##  - release
##
##build:
##  stage: build
##  script:
##    - update_pom_version
##    - mvn package spring-boot:repackage
##    - mv target/app.jar $PWD/docker
##    - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
##
##
##
##release:
##  stage: release
##  script:
##    - chart_build
##
##maven-deploy-snapshot:
##  stage: build
##  script:
##    - mvn clean install -Dmaven.springboot.skip=true -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_SNAPSHOT_REPOSITORY_ID}::default::${CHOERODON_SNAPSHOT_URL} -Ddeploy.classifier=exec
##  # 只有master, release和hotfix分支才发包
##  only:
##    refs:
##    - master
##    - /^.*hotfix.*$/
##    - /^.*release.*$/
##
##maven-deploy-release:
##  stage: build
##  script:
##    - mvn clean install -Dmaven.springboot.skip=true -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_RELEASE_REPOSITORY_ID}::default::${CHOERODON_RELEASE_URL} -Ddeploy.classifier=exec
##  only:
##    - tags
##
##
##.auto_devops: &auto_devops |
##  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
##  if [ "$http_status_code" != "200" ]; then
##    cat .auto_devops.sh
##    exit 1
##  fi
##  source .auto_devops.sh
##
##before_script:
##  - *auto_devops